name: build-unclog

on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string 
    outputs:
      artifact-name:
        description: "name of uploaded artifact"
        value: ${{ jobs.build_unclog.outputs.artifact-name}}

jobs:
  build-unclog:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact-namer.outputs.artifact-name }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o unclog -v .

    - name: Default binary name
      if: ${{ inputs.artifact-name != '' }}
      shell: bash
      run: |
        echo "UNCLOG_BINARY_NAME={{ $inputs.artifact-name }}" >> ${GITHUB_ENV}

    - name: Scoped name in PR
      if: ${{ inputs.artifact-name == '' && github.event_name == 'pull_request' }}
      shell: bash
      run: |
        echo "UNCLOG_BINARY_NAME=unclog-${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}
    - name: Scoped name on push
      if: ${{ inputs.artifact-name == '' && github.event_name == 'push' }}
      shell: bash
      run: |
        echo "UNCLOG_BINARY_NAME=unclog-${GITHUB_SHA}" >> ${GITHUB_ENV}

    - name: Set artifact-name output parameter
      id: artifact-namer
      shell: bash
      run: |
        echo "artifact-name=${UNCLOG_BINARY_NAME}" >> "$GITHUB_OUTPUT"

    - name: Upload unclog binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact-namer.outputs.artifact-name}}
        path: unclog
