# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: dogfood

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-changelog-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: build-unclog
        id: unclog-build
        uses: ./.github/actions/build-unclog

      - name: Download changelog check binary
        id: unclog-download
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806
        with:
          name: ${{ steps.unclog-build.outputs.artifact-name }}

      - name: Get new changelog files
        id: new-changelog-files
        uses: OffchainLabs/gh-action-changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b # v4.0.8
        with:
          files: |
            log/**.md

      - name: Run lint command
        shell: bash
        env:
          ALL_ADDED_MARKDOWN: ${{ steps.new-changelog-files.outputs.added_files }}
          #UNCLOG_BIN: ${{ steps.unclog-download.outputs.download-path}}/${{ steps.unclog-build.outputs.artifact-name }}
          #UNCLOG_DIR: ${{ steps.unclog-download.outputs.download-path}}
        run: |
          chmod +x unclog && ./unclog check -fragment-env=ALL_ADDED_MARKDOWN
