# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: dogfood

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-unclog:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.unclog-build.outputs.artifact-name }}
    steps:

    - name: Run unclog build
      id: unclog-build
      uses: ./.github/workflows/build-unclog.yml

  run-changelog-check:
    runs-on: ubuntu-latest
    needs: build-unclog

    steps:

      - name: Download changelog check binary
        id: unclog-download
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-unclog.outputs.artifact-name }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get new changelog files
        id: new-changelog-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            log/**.md

      - name: Run lint command
        shell: bash
        env:
          ALL_ADDED_MARKDOWN: ${{ steps.new-changelog-files.outputs.added_files }}
          UNCLOG_BIN: ${{ steps.unclog-download.outputs.download-path}}/${{ needs.build-unclog.outputs-artifact-name }}
        run: |
          chmod +x ${UNCLOG_BIN} && ./${UNCLOG_BIN} check -fragment-env=ALL_ADDED_MARKDOWN
