name: release
description: "automatically build unclog releases"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-unclog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: build-unclog
        uses: ./.github/actions/build-unclog
        with:
          artifact-name: unclog # This is the 'release' artifact name

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      shell: bash
      run: go build -o unclog -v .

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: unclog
        make_latest: "true"
